package bean;
// Generated 07/12/2023 14:36:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VeccProduto generated by hbm2java
 */
@Entity
@Table(name="vecc_produto"
    ,catalog="db_victor_cardoso"
)
public class VeccProduto  implements java.io.Serializable {


     private int idveccProduto;
     private VeccVendedor veccVendedor;
     private int veccCodigo;
     private String veccNome;
     private int veccQuantidade;
     private String veccDescricao;
     private double veccPreco;

    public VeccProduto() {
    }

	
    public VeccProduto(int idveccProduto, VeccVendedor veccVendedor, int veccCodigo, String veccNome, int veccQuantidade, String veccDescricao, double veccPreco) {
        this.idveccProduto = idveccProduto;
        this.veccVendedor = veccVendedor;
        this.veccCodigo = veccCodigo;
        this.veccNome = veccNome;
        this.veccQuantidade = veccQuantidade;
        this.veccDescricao = veccDescricao;
        this.veccPreco = veccPreco;
    }

   
     @Id 

    
    @Column(name="idvecc_produto", unique=true, nullable=false)
    public int getIdveccProduto() {
        return this.idveccProduto;
    }
    
    public void setIdveccProduto(int idveccProduto) {
        this.idveccProduto = idveccProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vecc_fk_vendedor", nullable=false)
    public VeccVendedor getVeccVendedor() {
        return this.veccVendedor;
    }
    
    public void setVeccVendedor(VeccVendedor veccVendedor) {
        this.veccVendedor = veccVendedor;
    }

    
    @Column(name="vecc_codigo", nullable=false)
    public int getVeccCodigo() {
        return this.veccCodigo;
    }
    
    public void setVeccCodigo(int veccCodigo) {
        this.veccCodigo = veccCodigo;
    }

    
    @Column(name="vecc_nome", nullable=false, length=45)
    public String getVeccNome() {
        return this.veccNome;
    }
    
    public void setVeccNome(String veccNome) {
        this.veccNome = veccNome;
    }

    
    @Column(name="vecc_quantidade", nullable=false)
    public int getVeccQuantidade() {
        return this.veccQuantidade;
    }
    
    public void setVeccQuantidade(int veccQuantidade) {
        this.veccQuantidade = veccQuantidade;
    }

    
    @Column(name="vecc_descricao", nullable=false, length=45)
    public String getVeccDescricao() {
        return this.veccDescricao;
    }
    
    public void setVeccDescricao(String veccDescricao) {
        this.veccDescricao = veccDescricao;
    }

    
    @Column(name="vecc_preco", nullable=false, precision=22, scale=0)
    public double getVeccPreco() {
        return this.veccPreco;
    }
    
    public void setVeccPreco(double veccPreco) {
        this.veccPreco = veccPreco;
    }



}


