package bean;
// Generated 07/12/2023 14:36:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VeccVenda generated by hbm2java
 */
@Entity
@Table(name="vecc_venda"
    ,catalog="db_victor_cardoso"
)
public class VeccVenda  implements java.io.Serializable {


     private int veccIdvenda;
     private VeccCliente veccCliente;
     private VeccVendedor veccVendedor;
     private String veccEndereco;
     private String veccProduto;
     private double veccPreco;


    public VeccVenda() {
    }

	
    public VeccVenda(int veccIdvenda, VeccCliente veccCliente, VeccVendedor veccVendedor, String veccEndereco, String veccProduto, double veccPreco) {
        this.veccIdvenda = veccIdvenda;
        this.veccCliente = veccCliente;
        this.veccVendedor = veccVendedor;
        this.veccEndereco = veccEndereco;
        this.veccProduto = veccProduto;
        this.veccPreco = veccPreco;
    }
   
     @Id 

    
    @Column(name="vecc_idvenda", unique=true, nullable=false)
    public int getVeccIdvenda() {
        return this.veccIdvenda;
    }
    
    public void setVeccIdvenda(int veccIdvenda) {
        this.veccIdvenda = veccIdvenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vecc_cliente", nullable=false)
    public VeccCliente getVeccCliente() {
        return this.veccCliente;
    }
    
    public void setVeccCliente(VeccCliente veccCliente) {
        this.veccCliente = veccCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vecc_fk_vendedor", nullable=false)
    public VeccVendedor getVeccVendedor() {
        return this.veccVendedor;
    }
    
    public void setVeccVendedor(VeccVendedor veccVendedor) {
        this.veccVendedor = veccVendedor;
    }

    
    @Column(name="vecc_endereco", nullable=false, length=45)
    public String getVeccEndereco() {
        return this.veccEndereco;
    }
    
    public void setVeccEndereco(String veccEndereco) {
        this.veccEndereco = veccEndereco;
    }

    
    @Column(name="vecc_produto", nullable=false, length=45)
    public String getVeccProduto() {
        return this.veccProduto;
    }
    
    public void setVeccProduto(String veccProduto) {
        this.veccProduto = veccProduto;
    }

    
    @Column(name="vecc_preco", nullable=false, precision=22, scale=0)
    public double getVeccPreco() {
        return this.veccPreco;
    }
    
    public void setVeccPreco(double veccPreco) {
        this.veccPreco = veccPreco;
    }




}


